//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wired8021xconfigurator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("wired8021xconfigurator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;EapHostUserCredentials xmlns=&quot;http://www.microsoft.com/provisioning/EapHostUserCredentials&quot;
        ///    xmlns:eapCommon=&quot;http://www.microsoft.com/provisioning/EapCommon&quot;
        ///    xmlns:baseEap=&quot;http://www.microsoft.com/provisioning/BaseEapMethodUserCredentials&quot;&gt;
        ///  &lt;EapMethod&gt;
        ///    &lt;eapCommon:Type&gt;25&lt;/eapCommon:Type&gt;
        ///    &lt;eapCommon:AuthorId&gt;0&lt;/eapCommon:AuthorId&gt;
        ///  &lt;/EapMethod&gt;
        ///  &lt;Credentials xmlns:eapUser=&quot;http://www.microsoft.com/provisioning/EapUserPropertiesV1&quot;
        ///      xmlns:xsi=&quot;http://www.w3.or [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string eap_user_info {
            get {
                return ResourceManager.GetString("eap_user_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;LANProfile xmlns=&quot;http://www.microsoft.com/networking/LAN/profile/v1&quot;&gt;
        ///  &lt;MSM&gt;
        ///    &lt;security&gt;
        ///      &lt;OneXEnforced&gt;false&lt;/OneXEnforced&gt;
        ///      &lt;OneXEnabled&gt;true&lt;/OneXEnabled&gt;
        ///      &lt;OneX xmlns=&quot;http://www.microsoft.com/networking/OneX/v1&quot;&gt;
        ///        &lt;cacheUserData&gt;true&lt;/cacheUserData&gt;
        ///        &lt;authMode&gt;user&lt;/authMode&gt;
        ///        &lt;EAPConfig&gt;
        ///          &lt;EapHostConfig xmlns=&quot;http://www.microsoft.com/provisioning/EapHostConfig&quot;&gt;
        ///            &lt;EapMethod&gt;
        ///              &lt;Type xmlns= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Wired_WinPE_PEAP_MSChapv2 {
            get {
                return ResourceManager.GetString("Wired_WinPE_PEAP_MSChapv2", resourceCulture);
            }
        }
    }
}
